### ISSUE TITLE
Should apply strikethrough text decoration

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#115]

**Comment by unitehenry** [comment]
@rach-m Absolutely!

I'd recommend checking out the *apply font style to content* test in ```demo/src/test.js``` and this should give you an idea of how to write this test. We'll want to interact with the ```#toolbar-strikethrough``` option.

Please reach out if you need any help!

**Comment by rach-m** [comment]
Awesome! Quick question- how do I run the test file to make sure it works correctly. I don't see a test script in the package.json

**Comment by unitehenry** [comment]
If you've set everything up by the [contributing guide](https://github.com/striven-erp/striven-editor/wiki/Contributing), then you can visit ```http://localhost:8080/``` and you'll see the tests being run in the browser.

**Comment by rach-m** [comment]
I put in a pull request to show my code but I am not sure why I am getting the error I am getting. I have outlined the issue more thoroughly in the PR
