### ISSUE TITLE
Should validate properly formatted url

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#128]
Use the ```se.validURL``` method that should return ```true``` for valid urls and ```false``` for invalid urls.

**Comment by sambhavjain9138** [comment]
Heyy
I would like to contribute to the issue. Can you please guide me?

**Comment by unitehenry** [comment]
@sambhavjain9138 Welcome to have you!

To see if you want to take this on, check out these two files:

1. ```src/striveneditor.js``` which contains the ```validURL``` method.
2. In the ```demo/src/test.js``` file see how the unit tests are being written.

If you think you can handle it, let me know and I will assign this issue to you! 😄

**Comment by sambhavjain9138** [comment]
okay sure. I'll check it. Thanks!

**Comment by sambhavjain9138** [comment]
Heyy @unitehenry 
I am able to understand the code, but because validURL function is alreay implemented in the src/striveneditor folder, I am not able to understand the contribution i need to make. Can you please guide me further. Thanks

Regards,
Sambhav

**Comment by unitehenry** [comment]
The need is for a unit test in the ```demo/src/test.js``` file.

You can write a test here that does the following:

1. Get an instance of the editor with ```getEditor```
2. Calls ```validURL``` and tests a valid and invalid string
3. Assert that the one string comes back valid and the other did not

**Comment by sambhavjain9138** [comment]
Sir, I am appending the following function in the regression test:
`it('should check if the input string is a valid URL', (done) => {
  const se = getEditor();
  const link=se.getcontent();
  assert.isTrue(se.validURL(link),link);
  done();
 });`

Is it the right way?

Regards,
Sambhav

**Comment by unitehenry** [comment]
There is no need to call ```getContent``` you can manually pass a string into ```validURL``` and just check for the result.

Also, let's try for both cases:

* A link that should be valid (returns ```true```)
* A link that shouldn't be valid (returns ```false```)

When both results come back as expected, pass the test.

**You are on the right track though!** 👍

**Comment by sambhavjain9138** [comment]
Hello sir
This is the following updated code:
` it('should check if the input string is a valid URL', (done) => {
  const se = getEditor();
  assert.isTrue(se.validURL('https://www/google.com'),'The string is a valid link');
  assert.isFalse(se.validURL('invalid.string'),'The string is an invalid link');
  done();
 });`

Is this the correct one?

Regards,
Sambhav Jain

**Comment by unitehenry** [comment]
Yeah this looks great! Submit a PR!

**Comment by sambhavjain9138** [comment]
Hello @unitehenry 
I made a PR request for the same. Please let me know if i did something wrong or if there are some tips for me to improve. 

Regards,
Sambhav
