### ISSUE TITLE
Should remove inline styles from element

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#130]
Use the ```se.pruneInlineStyles``` method to pass an element with inline styles that use ```style="position: static"``` and insure they removed from those elements.

**Comment by yerlantemir** [comment]
Hi, I want to contribute to this issue, could you give detailed explanation ?

**Comment by unitehenry** [comment]
@yerlantemir To see if you want to take this on, check out these two files:

1. ```src/striveneditor.js``` which contains the```pruneInlineStyles``` method.
2. In the ```demo/src/test.js``` file see how the unit tests are being written.

The test should look something like this:

1. Pass an HTML element with elements that have ```style="positon: static```
2. Take the returns element and test for any elements with ```[style="position: static"]````

If you think you can handle it, let me know and I will assign this issue to you! 😄

**Comment by yerlantemir** [comment]
`Take the returns element and test for any elements with [style="position: static"]` what do you mean by that ? Test should check if element has style property with 'position: static'?

**Comment by yerlantemir** [comment]
Okay, I got it, assign it to me

**Comment by yerlantemir** [comment]
@unitehenry could you write steps to build this project locally ? I am facing errors like this: 
` ERROR  Failed to compile with 1 errors                                                                                                                          18:40:38
This dependency was not found:

* @striven-erp/striven-editor in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save @striven-erp/striven-editor`

Steps to reproduce:

- clone project
- cd project
- npm i
- npm start

**Comment by unitehenry** [comment]
Try following this guide and let me know if you have any issues:
https://github.com/striven-erp/striven-editor/wiki/Contributing

**Comment by yerlantemir** [comment]
thanks!

**Comment by yerlantemir** [comment]
@unitehenry I added testcase, but it fails, is it ok?

**Comment by unitehenry** [comment]
The idea is that tests should pass to make sure the editor is in a stable state. You can open the PR and we can take a look at it if you want.

It should come down to ```assert.isNotNull(elFromPruneInlineStyles.querySelector('style="position: static"'), 'no static position elements');``` which should pass when ```pruneInlineStyles``` worked correctly.

**Comment by yerlantemir** [comment]
@unitehenry what is wrong with my solution?
