### ISSUE TITLE
Should format bytes in human readable string

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#131]
Write a test for the ```se.formatBytes``` method which passes bytes and returns a nicely formatted string of the size.

**Comment by felipehfs** [comment]
Can I take it?

**Comment by unitehenry** [comment]
@felipehfs You sure can!

Check out the ```demo/src/test.js``` file in ```dev``` branch and checkout the *Unit Tests* section.
Also refer to the **CONTRIBUTING** section of the wiki to set up your development environment.

Feel free to reach out for help 😄
