### ISSUE TITLE
Should open/close link menu

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#132]
Ensure that ```se.openLinkMenu``` opens the editor's link menu and ```se.closeLinkMenu``` closes it.

**Comment by m1ga** [comment]
I would like to help here!

**Comment by unitehenry** [comment]
@m1ga Happy to have you!

To see if you want to take this on, check out these two files:

1. ```src/striveneditor.js``` which contains the```openLinkMenu``` and ```closeLinkMenu``` method.
2. In the ```demo/src/test.js``` file see how the unit tests are being written.

The test should look something like this:

1. Call the ```se.openLinkMenu``` function
2. Make sure the menu is open and visible
3. Call the ```se.closeLinkMenu``` function
4. Make sure the menu is not visible

If you think you can handle it, let me know and I will assign this issue to you! 😄
