### ISSUE TITLE
Should denormalize camelcase string

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#140]
Write a unit test for ```denormailzeCamel``` from the ```utils.js``` file which takes a camelCase string and returns a readable string.

Ex: *camelCaseString* should be *Camel Case String*

**Comment by SuchismitaDhal** [comment]
Hey! I will like to create the unit test. Can you assign the issue to me?

**Comment by unitehenry** [comment]
@SuchismitaDhal Thanks for your help! 😄

**Comment by SuchismitaDhal** [comment]
Should I make a new directory "tests" in the src directory?

**Comment by unitehenry** [comment]
Check out these two files:

1. ```src/utils.js``` which contains ```denormalizeCamel``` method.
2. In the ```demo/src/test.js``` file see how the unit tests are being written
   * This is where the test should be writted.
