### ISSUE TITLE
Cross-Browser Testing

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#25]
Test the editor in different browsers.

- [x] Edge
- [x] Chrome
- [x] Firefox
- [x] Safari

**Comment by unitehenry** [comment]
**Firefox**

Not executing ```document.execCommand```
This might be an issue with the ```activeElement```

**Comment by mushtaq96** [comment]
Hey can i take this issue!

**Comment by unitehenry** [comment]
@mushtaq96 That would be awesome!

Just comment any issues you can find. For now, we are just trying get all of the ```minimal```  options working across Edge, Safari, Firefox, and Chrome. But feel free to check all the extensible options with ```minimal``` set to ```false```.

Let me know if you have any questions and just document your findings here!

**Comment by unitehenry** [comment]
Also, I have already made issue of #34

**Comment by mushtaq96** [comment]
All right.. Thanks, I will get back to you if any further questions.

**Comment by mushtaq96** [comment]
Just a quick question, these tests are to be independent of the OS right?

**Comment by unitehenry** [comment]
@mushtaq96 It wouldn't hurt to consider OS, but just testing for cross-browser issues is good enough.

**Comment by mushtaq96** [comment]
Okay.
