### ISSUE TITLE
Insert entire link when no selection is provided

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#28]
```js
const range = this.getRange();

if(range.startOffset === range.endOffset){
     // Insert the entire link (range.insertNode?)
}
```

**Comment by theparselmouth** [comment]
can I take this up ?

**Comment by unitehenry** [comment]
@theparselmouth Yes, thanks!

**Comment by theparselmouth** [comment]
not sure if I understood the requirement correctly. Could you just check the PR and comment if anything else is needed ?

**Comment by theparselmouth** [comment]
Hey sorry for the delay. was held up. My console.log statements don't seem to be reflecting in the local test environment and I have no idea what I am doing wrong. Anyway, the problem seems to be that linkValue is returned as null for Firefox. Any ideas why this is ?

**Comment by unitehenry** [comment]
@theparselmouth Sorry for the late response. This one got lost in my email.

I'm not too sure why ```linkValue``` is evaluating null as it is just referencing the ```input.value``` for the link menu input. In Firefox, my advice is to look somewhere here maybe...

```js
window.getSelection().removeAllRanges();
window.getSelection().addRange(this.range);

if (this.isFirefox || this.isEdge) {
     const linkNode = document.createTextNode(linkValue);
     this.range.insertNode(linkNode);
     this.range.selectNode(linkNode);

     document.execCommand("createLink", false, linkValue);
}
```

I feel like something along these lines might work, but I'm just thinking hypothetically. So please let me know what you come across.

**Comment by unitehenry** [comment]
Also, feel free to reach out for more help if you get stuck! This isn't one of the most *clean-cut* solutions.
