### ISSUE TITLE
Create a test branch

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#35]
Update ```CONTRIBUTING``` to explain the development process...

1. Fork this repository
2. Work on ```test``` branch
3. Open PR to test

We will merge ```test``` branch to ```dev``` and then publish to ```master```

**Comment by fsjoyti** [comment]
Hi I just added a pull request to dev branch. Let me know if this how I am supposed to do it.

**Comment by clussell** [comment]
Could I take this one?

**Comment by unitehenry** [comment]
@clussell Yes, thanks for taking up this documentation issue!
