### ISSUE TITLE
Don't include remove format option on minimal toolbar

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#42]
When ```minimal``` is set to ```true```, do not show the ```#toolbar-removeFormat``` option on the ```.toolbar```.

![image](https://user-images.githubusercontent.com/29406771/66924231-403a4800-eff8-11e9-8312-06e42a4a5eee.png)

**Comment by carlosnufe** [comment]
I take this

**Comment by unitehenry** [comment]
@carlosnufe Thanks!
