### ISSUE TITLE
Edge Browser does not allow drop files to upload

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#44]
Is there a better way to do this? How is it that apps like Gmail are able to drop files?

**Comment by unitehenry** [comment]
![image](https://user-images.githubusercontent.com/29406771/66924510-bfc81700-eff8-11e9-9214-4d741784c42d.png)

**Comment by unitehenry** [comment]
@neptunecentury You are the windows guy... why is this?

**Comment by neptunecentury** [comment]
Edge supports drag and drop. I followed this tutorial here
https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/File_drag_and_drop

Codepen that works in Edge:
https://codepen.io/neptunecentury/pen/xxxOWmW

View the console to see the dropped files.

**Comment by unitehenry** [comment]
@neptunecentury Thanks for looking into this.

This was the solution in case you we wondering. The default behavior must disable file drops in Edge.

```js
this.body.ondragover = e => e.preventDefault();
```
