### ISSUE TITLE
Remove dist folder from git

### ISSUE THREAD

**Issue by waghcwb** [striven-erp/striven-editor#58]
I think we should not be committing the `dist` folder, instead we can use the `npm prepare` lifecycle

**Comment by unitehenry** [comment]
No ```dist``` should be tracked in the repo at all?

The ```npm prepare``` script would bundle with webpack, generate a ```dist```, and then publish to npm correct?

**Comment by waghcwb** [comment]
@unitehenry 
I think we won't need it.. If we put something like "npm run build" on the `prepare` script when the user run `npm install` npm will automatically build the code.

**Comment by unitehenry** [comment]
@waghcwb 

I agree that an ```npm prepare``` script should be provided, but I think keeping the ```dist``` folder in the repo is appropriate. If someone wants to download the project ```.zip```, then I want to have that option provided.

**Comment by waghcwb** [comment]
@unitehenry 

I think its better to create a [release](https://help.github.com/en/github/administering-a-repository/creating-releases) with the zip file. But its just a matter of choice.. Commiting the dist folder will make the final package bigger too.

**Comment by sanjogs** [comment]
I agree with removing dist from the source control, and adding it as a release

**Comment by unitehenry** [comment]
I've assignment myself this task. I agree, taking the ```dist``` folder out of the repo and having it on the release is best.

**Comment by unitehenry** [comment]
@waghcwb I have removed the ```dist``` folder but and made it available via **Releases**

I am not sure if this is the correct way to implement ```npm prepare```. Thoughts?

```json
"prepare": "npx webpack --mode=\"production\""
```

**Comment by waghcwb** [comment]
@unitehenry 
We can reuse the `build` script:

```js
{ "prepare": "npm run build" }
```

**Comment by unitehenry** [comment]
@waghcwb Ok, but this behavior should generate a ```dist``` folder for publish, correct?

**Comment by unitehenry** [comment]
@waghcwb Thanks for the suggestion. I removed the ```dist``` folder from the repo and added a ```.zip``` in the release notes. There is now a ```.npmignore``` file that includes ```dist``` in the publish and an ```npm prepare``` script that run our ```build``` script in ```package.json```.

Thanks for the suggestion it really helps the development flow!
