### ISSUE TITLE
Pasted urls should become link

### ISSUE THREAD

**Issue by sanjogs** [striven-erp/striven-editor#59]

**Comment by unitehenry** [comment]
Whoever takes this on, this will get you started...

```js
this.body.onpaste = e => {
     e.clipboardData // more code here
}
```

Can't remember off the top of my head. But essentially, once the editor recognizes pasted content as a link ( ```validURL``` ), then you can use ```document.execCommand('createLink')``` to create a link.

**Comment by An0u** [comment]
@ unitehenry Can I take this on?

**Comment by unitehenry** [comment]
@An0u Happy Hacking! 🎃

**Comment by unitehenry** [comment]
https://github.com/striven-erp/striven-editor/commit/85abe05c11947cfc1e7da7559edad0e500eeb90f
