### ISSUE TITLE
Change placeholder from p element to css ::after

### ISSUE THREAD

**Issue by neptunecentury** [striven-erp/striven-editor#74]
Placeholder is currently a p element. This causes an issue when you directly click on it as the focus is not passed to the body element. Also, there seems to be a click handler listening to it and when you click the Placeholder, it causes error with selection range.

This should be changed to use CSS ::after for an :empty body

**Comment by unitehenry** [comment]
@sanjogs Took care of it.
https://github.com/striven-erp/striven-editor/commit/e5a171d1413f3f6bd979127d9fa92eb6074165b0
