### ISSUE TITLE
Implement Sass for CSS

### ISSUE THREAD

**Issue by waghcwb** [striven-erp/striven-editor#80]
@unitehenry 

What you think of using sass for the css? If the answer is yes, can I get it?

**Comment by unitehenry** [comment]
@waghcwb 

What *problem* does sass solve?

**Comment by waghcwb** [comment]
@unitehenry 
We can make the styles more customizable to the developers that use the lib with variables to customize colors, fonts, margins, etc.

**Comment by unitehenry** [comment]
Let's see what @sanjogs thinks.

**Comment by sanjogs** [comment]
I think SASS will probably make our css better, but even when using SASS I think the CSS will already be be compiled into the dist output, so i didn't understand how users will be able to customize the variables. @unitehenry  @waghcwb

**Comment by waghcwb** [comment]
@sanjogs 
We can refactor the css files, so we can have a `variables.scss` with the colors and other customizations, so the users can change the values and make custom themes, also we can deliver custom pre-compiled stylesheets.

**Comment by sanjogs** [comment]
Okay, let's do it, by default we want the colors and styles that we currently have. I've assigned this to you. Thanks
