### ISSUE TITLE
Clicking buttons inside the image and link popup is submitting the form. 

### ISSUE THREAD

**Issue by sanjogs** [striven-erp/striven-editor#90]
Expected: Clicking on Close and Insert button should not submit the form

Resolution: Add type="button" attribute to these buttons so the form is not submitted.

**Comment by sanjogs** [comment]
@unitehenry  Assigned this to you.

**Comment by unitehenry** [comment]
@sanjogs I think I noticed this too. Is this what you're referring to?

![editor-bug](https://user-images.githubusercontent.com/29406771/67897366-9cdb4e00-fb34-11e9-8e9a-cbcda43b8d8f.gif)

**Comment by unitehenry** [comment]
https://github.com/striven-erp/striven-editor/commit/0ba9d8eda802c5238553b1b10695262e82291c56

**Comment by sanjogs** [comment]
@unitehenry  Awesome, thanks
