### ISSUE TITLE
Large floating menu for really small editors

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#92]
![image](https://user-images.githubusercontent.com/29406771/70654106-aa9bed00-1c23-11ea-8089-eca83041ec3b.png)

**Comment by unitehenry** [comment]
@sanjogs I think I'll use [this](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver)

**Comment by unitehenry** [comment]
https://github.com/striven-erp/striven-editor/commit/f996050dc102b7e0e08ac3b2951fa9a4d946c0bc

**Comment by sanjogs** [comment]
wow this looks neat!

**Comment by sanjogs** [comment]
This is not supported across all major browsers though, we need fallback implementation

**Comment by unitehenry** [comment]
https://github.com/que-etc/resize-observer-polyfill

**Comment by unitehenry** [comment]
*added the polyfill*

https://github.com/striven-erp/striven-editor/commit/0a756a29c1d7b43cd878b1678b8ef6e1d02eb7d9
